name: Bump Project Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump Type (see https://github.com/vers-one/dotnet-project-version-updater?tab=readme-ov-file#version-required)'
        required: true
        default: '*.*.^'
        type: string

jobs:
  bump-project-version:
    uses: SevenSoftware7/publish-dotnet-packages-to-nuget/.github/workflows/bump-version.yml@master
    with:
      bump-type: ${{ github.event.inputs.bump-type }}

  dispatch-release:
    needs: bump-project-version
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch release workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: release
          client-payload: '{"commit_sha": "${{ needs.bump-project-version.outputs.commit }}"}'